# 4

admin_certificate_edit:
  path: /admin/cert/edit/{cert}
  defaults: { _controller: "MasterAdminBundle:Admin:editCertificate" }

admin_certificate_delete:
  path: /admin/cert/delete/{cert}
  defaults: { _controller: "MasterAdminBundle:Admin:deleteCertificate" }

admin_review_edit:
  path: /admin/review/edit/{review}
  defaults: { _controller: "MasterAdminBundle:Admin:editReview" }

admin_review_delete:
  path: /admin/review/delete/{review}
  defaults: { _controller: "MasterAdminBundle:Admin:deleteReview" }

admin_tour_edit:
  path: /admin/tour/edit/{tour}
  defaults: { _controller: "MasterAdminBundle:Admin:editTour" }

admin_tour_delete:
  path: /admin/tour/delete/{tour}
  defaults: { _controller: "MasterAdminBundle:Admin:deleteTour" }

# 3

admin_certificate_add:
  path: /admin/cert/add
  defaults: { _controller: "MasterAdminBundle:Admin:addCertificate" }

admin_review_add:
  path: /admin/review/add
  defaults: { _controller: "MasterAdminBundle:Admin:addReview" }

admin_tour_add:
  path: /admin/tour/add
  defaults: { _controller: "MasterAdminBundle:Admin:addTour" }

admin_certificates:
  path: /admin/certificates
  defaults: { _controller: "MasterAdminBundle:Admin:certificates" }

admin_reviews:
  path: /admin/reviews
  defaults: { _controller: "MasterAdminBundle:Admin:reviews" }

admin_security_login:
  path: /admin/login
  defaults: { _controller: "MasterAdminBundle:Admin:login" }

admin_security_login_check:
  path: /admin/login-check

admin_security_logout:
  path: /admin/logout

# 1

admin_index:
  path: /admin
  defaults: { _controller: "MasterAdminBundle:Admin:index" }

site_general_booking:
  path: /booking
  defaults: { _controller: "MasterSiteBundle:General:booking" }

site_general_contacts:
  path: /contacts
  defaults: { _controller: "MasterSiteBundle:General:contacts" }

site_general_faq:
  path: /faq
  defaults: { _controller: "MasterSiteBundle:General:faq" }

site_general_flights:
  path: /flights
  defaults: { _controller: "MasterSiteBundle:General:flights" }

site_general_landing1:
  path: /landing1
  defaults: { _controller: "MasterSiteBundle:General:landing1" }

site_general_landing2:
  path: /landing2
  defaults: { _controller: "MasterSiteBundle:General:landing2" }

site_general_landing3:
  path: /landing3
  defaults: { _controller: "MasterSiteBundle:General:landing3" }

site_general_landing4:
  path: /landing4
  defaults: { _controller: "MasterSiteBundle:General:landing4" }

site_general_landing5:
  path: /landing5
  defaults: { _controller: "MasterSiteBundle:General:landing5" }

site_general_loyalty:
  path: /loyalty
  defaults: { _controller: "MasterSiteBundle:General:loyalty" }

site_general_reviews:
  path: /reviews
  defaults: { _controller: "MasterSiteBundle:General:reviews" }

site_general_visa:
  path: /visa
  defaults: { _controller: "MasterSiteBundle:General:visa" }

site_general_index:
  path: /
  defaults: { _controller: "MasterSiteBundle:General:index" }