security:
  encoders:
    Master\SystemBundle\Entity\User: sha1
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
  providers:
    admin_provider:
      entity: { class: Master\SystemBundle\Entity\User, property: username }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    admin_login:
      pattern: ^/admin/login$
      anonymous: ~
    admin:
      pattern: ^/admin
      form_login:
        provider: admin_provider
        login_path: admin_security_login
        check_path: admin_security_login_check
        username_parameter: login[username]
        password_parameter: login[password]
        target_path_parameter: login[targetpath]
        default_target_path: admin_index
        remember_me: true
      remember_me:
        key: "%secret%"
        lifetime: 86400
        path: /
        remember_me_parameter: login[rememberme]
      logout:
        path: admin_security_logout
        target: admin_security_logout
    site:
      pattern: ^/
      anonymous: ~
  access_control:
    - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }