security:
  encoders:
    Master\SystemBundle\Entity\User: bcrypt
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
  providers:
    admin_provider:
      entity: { class: Master\SystemBundle\Entity\User, property: username }
    site_provider:
      entity: { class: Master\SystemBundle\Entity\User, property: username }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
#    admin_login:
#      pattern: ^/login$
#      anonymous: ~
#    admin:
#      pattern: ^/
#      host: "secured.%country_domain%"
#      form_login:
#        provider: admin_provider
#        login_path: admin_security_signin
#        check_path: admin_security_signcheck
#        username_parameter: signin[username]
#        password_parameter: signin[password]
#        target_path_parameter: signin[targetpath]
#        default_target_path: admin_information_index
#        remember_me: true
#      remember_me:
#        key: "%secret%"
#        lifetime: 86400
#        path: /
#        domain: "%country_domain%"
#        remember_me_parameter: signin[rememberme]
#      logout:
#        path: admin_security_signout
#        target: admin_security_signin
    site:
      pattern: ^/
      anonymous: ~
  access_control:
#    - { path: ^/signin$, host: "secured.%country_domain%", roles: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/, host: "secured.%country_domain%", roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }