parameters:
#  empty

services:
  bordel.listener.pre_controller:
    class: Master\SystemBundle\EventListener\PreControllerListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }